import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import { Control } from './Control';

export const metadata = {
  title: '아이고',
  description: 'Generated by 태형',
};

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {
    cache: 'no-cache',
  });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>

        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control></Control>
      </body>
    </html>
  );
}
